### ISSUE TITLE
sbt gen-ensime Error

### ISSUE THREAD

**Issue by omarimayerswalker** [ensime/ensime-sbt#107]
When I trying to create a ```.ensime``` file I get the following error messages:

```
[info] Loading global plugins from /home/user/.sbt/0.13/plugins
[info] Set current project to scala (in build file:/home/user/code/scala/)
[error] Not a valid command: gen-ensime
[error] Not a valid project ID: gen-ensime
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: gen-ensime
[error] gen-ensime
[error]           ^
```
in my plugin directory I have the following code:
```
resolvers += Resolver.sonatypeRepo("snapshots")

// for ensime
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.7-SNAPSHOT")
```
It is located here:
```
/home/user/.sbt/0.13/plugins/plugins.sbt
```
sbt version:  0.13.1
scala version: 2.10.4

Thanks for the help.

**Comment by fommil** [comment]
check the README again

**Comment by avdv** [comment]
@fommil His setup looks good to me, exactly as outlined in the README. Do you see anything wrong?

@omarimayerswalker What's the output of `sbt about`? Does it list the EnsimePlugin as an available plugin? I think you might just as well try a release version, like "0.2.1", instead of a SNAPSHOT (you could drop the `resolvers += ...` line then).

**Comment by fommil** [comment]
Version

**Comment by omarimayerswalker** [comment]
@avdv I was using Fedora's scala/sbt package. After not getting anywhere with it all day I decided to uninstall it and use the latest versions of scala and sbt. Everything is working now.

**Comment by goungoun** [comment]
sbt reload plugins might resolve this issue.

$ sbt
> reload plugins
