### ISSUE TITLE
ensime-sbt conflicts with project scalariform.sbt

### ISSUE THREAD

**Issue by tysonjh** [ensime/ensime-sbt#123]
Since version 0.1.7 there has been a conflict between ensime-sbt and a project's sclariform.sbt file. Refer to test project: https://github.com/tysonjh/ensime-sbt-scalariform

Compiling the test project with 0.1.5 works fine. Compiling with 0.1.7, 0.2.0, 0.2.1 results in the following error,

.../test/src/main/scala/Test.scala:4: value % is not a member of (String, Int)
[error]     map += ("blah" → (1 + 1) % 1)
[error]                              ^
[error] one error found
[error] (compile:compile) Compilation failed

**Comment by fommil** [comment]
https://github.com/mdr/scalariform/issues/137

**Comment by fommil** [comment]
Workaround is to use source  install of ensime-sbt and then you can control exact versions. But check back for updates regularly (especially next few days, performance improvement coming). The compile failure sounds like a bug upstream. Please report this failure with daniel-trinh's fork of scalariform.

This whole scalariform things kills me. I've wasted so which time on it, all because the author went AWOL and hasn't transferred the repo to an org. But we're fixing it Q1 of 2016.

**Comment by tysonjh** [comment]
Thanks for the quick reply and workaround, much appreciated.

**Comment by fommil** [comment]
I created an FAQ about this at #124

**Comment by fommil** [comment]
I'm removing our dependency on sbt-scalariform in the next release (tonight).
