### ISSUE TITLE
all my code is reformatted!

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#124]
If you aren't using scalariform it's this:

* https://github.com/daniel-trinh/sbt-scalariform/issues/24

if you are using scalariform to reformat your code, then its this:

* happens if you were using https://github.com/sbt/sbt-scalariform
* caused by regressions introduced in https://github.com/daniel-trinh/scalariform and https://github.com/daniel-trinh/sbt-scalariform
* blocked on https://github.com/mdr/scalariform/issues/137

There is no easy workaround at the moment, but you may be lucky enough to be able to force a specific version of scalariform in your sbt build config. Ask an sbt expert.

**Comment by fommil** [comment]
scalariform is in such a mess right now, I think maybe we should just not try to integrate with sbt-scalariform until it gets fixed. I'll fix this tonight.

**Comment by daniel-trinh** [comment]
Adding `addSbtPlugin("org.scalariform" %% "sbt-scalariform" % "1.5.1")` to a project is going to by default auto format your code, this is the current intended behavior. Can you elaborate what's going on here? One thing you could potentially do is to disable the sbt-scalariform plugin on the ensime project.

**Comment by gaydenko** [comment]
@daniel-trinh , autoformatting conflicts with source editors: they treat it as external modification. Any reformatting must be explicitly started, I guess. In this sense, adding the plugin is just an adding the opportunity to format rather than a command to format.

Any unintentional opportunity of source modification is just a crime :)

**Comment by fommil** [comment]
It's also a really big regression that catches people unawares.

**Comment by daniel-trinh** [comment]
@gaydenko Adding the plugin and not having it auto format is a strange usecase for single build projects, since prior to adding autoplugin behavior, by adding sbt-scalariform to the project build, it would by default auto format. However I do see your point in multi project sbt builds, since some projects might not want scalariform enabled.

I think the simplest solution is to do one of the following:

* Have the sbt-scalariform autoplugin require explicit enabling per project configuration
* Educate users of the difference in the latest version and suggest the use of plugin disabling when its not desired by adding it to the sbt-scalariform readme of this change

Example:
```
lazy val util = (project in file("util")).
  enablePlugins(FooPlugin, BarPlugin).
  disablePlugins(plugins.IvyPlugin).
  settings(
    name := "hello-util"
  )
```

This would allow users to pick and choose per project in an sbt build where sbt-scalariform is enabled.

Also, in prior versions in sbt-scalariform, it was possible to have sbt-scalariform enabled but the auto formatting disabled by using `defaultScalariformSettings` instead of `scalariformSettings`. The current autoplugin behavior is set to use `scalariformSettings`, and can still be overridden in a similar fashion to before.

For the time being, I'll add an update to the sbt-scalariform readme warning about the autoplugin behavior.

I still haven't gotten my question answered though -- is ensime-sbt compiled with sbt-scalariform 1.5.x autoformatting code for people who are using ensime-sbt indirectly and aren't using sbt-scalariform? That is strange and unintended. I'd like to know more about how that is happening if that is the case.

**Comment by gaydenko** [comment]
@daniel-trinh , sorry, I'm not aware of ensime-sbt mechanics. I guess @fommil is aware of everything :)

**Comment by fommil** [comment]
@daniel-trinh I've disabled all dependency on `sbt-scalariform` now because this brought with it such a large regression. I'd like to depend on some version of `sbt-scalariform` so that we can automatically infer project-wide formatting settings but we can't do that until you release a version of `sbt-scalariform` that does not autoreformat.

In addition, `sbt-scalariform` should be able to handle older versions of `scalariform` so that users can use `dependencyOverride` to force an old version, if that is what their project/branch requires (as a workaround until all regressions/defaults in Scalariform itself are addressed)

I recommend doing the following in `sbt-scalariform`:

1. do no reformat by default
2. have a default set of settings that works at runtime with the old version of scalariform
3. provide an optional set of defaults which provide the new recommended defaults

and in scalariform

1. address all regressions, with the defaults resulting in the same behaviour as the old version. Genuine cornercase bugfixes in formatting are tolerable and do not require regression support.
2. provide the implementation of the recommended defaults (i.e. full agreement with the Scala formatting guidelines, which may result in reformatting between releases as features are added)

I recently wrote a test suite for `ensime-sbt` which may be something you/we (you, me plus `scala-ide`) would like to make use of going forwards. The latest timeline on `scala-ide` ownership is Q1 of 2016 but we can do some of the above in the meantime.

I hope that all makes sense! :-) Hopefully we can recover from the mess that Matt has left us in: going AWOL without transferring the repository to the community.
