### ISSUE TITLE
revert include source/javadoc in preference for user setting

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#165]
@jodersky introduced a feature flag to allow skipping sources / javadocs but @dwijnand pointed out that it is possible to set this on a per-user basis for all projects, which I feel is far more appropriate than hacking around it in our plugin:

https://github.com/ensime/ensime-sbt/blob/2f532c1b0d6c4d609d57bf65d69b000b9e375af5/src/main/scala/EnsimePlugin.scala#L33-L38

**Comment by dwijnand** [comment]
For reference I was talking about the fact that I have globally:

```scala
transitiveClassifiers in Global := Seq(Artifact.SourceClassifier) // don't download javadoc
```

in `~/.sbt/0.13/nojavadocs.sbt` so `updateClassifiers` never tries to download javadocs for me.

**Comment by jodersky** [comment]
My PR #114 was a hack so if you have any cleaner solutions I would be glad to see it go.

@dwijnand I also considered the `transitiveClassifiers` option before submitting the PR, however I decided to not modify that setting. My reasoning was that `transitiveClassifiers` is not restricted to ensime, and changing it globally could have unwanted effects. What if you define it to be empty but a project overrides it because it needs it for some unrelated task?

It seems that the underlying problem is a scoping issue, maybe this could be solved in scoping `transitiveClassifiers` to an "ensime" config?

**Comment by fommil** [comment]
@jodersky fancy having another shot at it? I much prefer reusing existing keys

**Comment by jodersky** [comment]
Sure, my plan is to scope `transitiveClassifiers` to the gen-ensime/gen-ensime-meta tasks and default to transitiveClassifiers in global config.
This approach would offer more fine grained control and would allow downloading (or not) different classifiers for different tasks.

**Comment by jodersky** [comment]
My solution would have been to add something similar to the `megaUpdate` task:

```scala
EnsimeKeys.megaUpdate <<= Keys.state.flatMap { implicit s0 =>

      //addition here: transitiveClassifiers is modified only for the megaUpdate task
      val s = Project.extract(s0).append(
        Seq(transitiveClassifiers := (transitiveClassifiers in megaUpdate).value),
        s0
      )

      val projs = Project.structure(s).allProjectRefs
      log.info("ENSIME update. Please vote for https://github.com/sbt/sbt/issues/2266")
      for {
        updateReport <- update.forAllProjects(s, projs)
        _ = log.info("ENSIME updateClassifiers. Please vote for https://github.com/sbt/sbt/issues/1930")
        updateClassifiersReport <- updateClassifiers.forAllProjects(s, projs)
      } yield {
        projs.map { p =>
          (p, (updateReport(p), updateClassifiersReport(p)))
        }.toMap
      }
    }
```
and set `transitiveClassifiers in megaUpdate` to the default value in global.

However, thinking more about it, it might not be worth the effort since it would also override any project specific settings (i.e. it would not be possible to have different classifiers for different subprojects).

I think the easiest solution at the moment is to go with @dwijnand's proposition.
In the future, should a separate value for `transitiveClassifiers` in `megaUpdate` ever be needed, the above solution can easily be implemented.
