### ISSUE TITLE
scala library (and jars/sources) not resolved for 2.10 projects

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#283]
regression, looks like 2.10 projects are reusing sbt's resolved scala-library (without sources or docs) instead of trying to resolve from the explicit coursier Repositories.

@alexarchambault does this ring a bell? this will be happening for normal scala projects just through the basic `updateClassifiers` mechanism

**Comment by fommil** [comment]
reported upstream https://github.com/alexarchambault/coursier/issues/402 but I'm still not 100% sure what the problem is.

**Comment by fommil** [comment]
our tests missed this because we don't have any tests projects using the default scala version. when there is a fix, we should change `simple-build-scala` to use the default scala version.

**Comment by alexarchambault** [comment]
@fommil That totally rings a bell. I made sbt-coursier provide SBT's resolved libraries, as SBT was putting them in the applications classpath anyway (via some classloader magic). Which should make `updateClassifiers` fail to find sources / javadoc for these.

The fix would involve just making the special internal repository of sbt-coursier, which provides SBT's resolved libs, a bit more evolved, so that it can fetch sources / javadocs from the other repositories.

**Comment by fommil** [comment]
ok, good to hear. As a workaround for now, is there any way to force it to ignore the boot jars? I don't believe the boot jars are added if `fork:=true`
