### ISSUE TITLE
unresolved dependency: org.ensime#sbt-ensime;1.12.5: not found

### ISSUE THREAD

**Issue by mruediger** [ensime/ensime-sbt#304]
### Steps to reproduce

1. add resolvers += Resolver.sonatypeRepo("snapshots")`  to `~/.sbt/0.13/plugins.sbt`
2. add `addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.5")` to `~/.sbt/0.13/plugins.sbt`
3. run `sbt ensimeConfig` in an project just created with `sbt new sbt/scala-seed.g8`

### Expected behaviour

the creation of a `.ensime` file

### Actual behaviour

`sbt` cannot find `sbt-ensime-1.12.5.pom`

```
[info] Resolving org.ensime#sbt-ensime;1.12.5 ...
[warn] 	module not found: org.ensime#sbt-ensime;1.12.5
[warn] ==== local: tried
[warn]   /home/bag/.ivy2/local/org.ensime/sbt-ensime/scala_2.12/sbt_0.13/1.12.5/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/ensime/sbt-ensime_2.12_0.13/1.12.5/sbt-ensime-1.12.5.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/ensime/sbt-ensime_2.12_0.13/1.12.5/sbt-ensime-1.12.5.pom
```

Upon further investigation I saw that on sonatype there is no https://oss.sonatype.org/content/repositories/snapshots/org/ensime/sbt-ensime_2.12_0.13/ but only https://oss.sonatype.org/content/repositories/snapshots/org/ensime/sbt-ensime_2.10_0.13/

Is my version of `sbt` to new? I am using `sbt-0.13.13.1-1`.

**Comment by fommil** [comment]
Read the docs again. The bit you missed is in bold text.

**Comment by mruediger** [comment]
Thanks! m) I will have a look if I can rephrase that part of the documentation to make it more obvious and send out a PR. Its a bit hard to get, as you might have noticed. I am no native English speaker which might be the cause.

**Comment by juiceo** [comment]
@fommil after installing sbt with homebrew, I have no such directory as `~/.sbt/0.13/plugins` with a file called plugins.sbt. I tried creating that directory and file, but still get a resolution error when running `sbt`.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.ensime#sbt-ensime;1.12.15: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.ensime:sbt-ensime:1.12.15 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.ensime:sbt-ensime:1.12.15 (scalaVersion=2.12, sbtVersion=1.0) (/Users/juuso/.sbt/1.0/plugins/plugins.sbt#L1-2)
[warn] 		  +- org.scala-sbt:global-plugins:0.0 (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.ensime#sbt-ensime;1.12.15: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2306)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: org.ensime#sbt-ensime;1.12.15: not found
```

**Comment by fommil** [comment]
sbt 1.0. This is documented in that section.

**Comment by juiceo** [comment]
@fommil you do realise that if the documentation gave me the answers I needed, I would not be asking you here. Seeing as you are taking the time to answer these questions, the very least you could do is link to the relevant section in the docs, so that I know I am not missing anything. Frankly, your attitude towards answering this and other questions is arrogant, and I will be moving on to another project where I feel like issues are treated with due respect.

**Comment by jozanek** [comment]
Hi @lappalj4, sbt 1.0 is not supported yet. Quoting from docs: `If it says unresolved dependency or command not found then ensure that the sbt version in project/build.properties is 0.13.16 until sbt 1.0 support is added.`
You are right that @fommil is not explicit and expects users to dig a bit (read docs properly as he spent a lot of time writing it), but you will get use to it after some time :)
Would you like to help and try to make it work for sbt 1.0? Also see #237.

**Comment by fommil** [comment]
@lappalj4 You didn't read the docs properly, nor did you follow the troubleshooting guide. I gave you a nudge to go read them, and a hint about what was wrong (sbt 1.0). Refusing to follow these steps will not get you any help around here.

I don't want to have to interact with entitled users like you, and I don't want you hassling the good people around here who are contributing (in whatever capacity, be it with code, funding or encouragement) to make ensime better. I also don't care how many users ensime has, nor do I care about resolving issues from random dudes on the internet: that is not the goal of this project nor me personally. If your ego can't handle being told that what you're looking for is documented, you will not fit in around here.

I suggest you read https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d

**Comment by fommil** [comment]
@jozi-k it's ok, the sponsored developer is currently working on sbt 1.0 support :wink: I don't know how long it will take, but I am looking forward to it.

**Comment by jrd-rocks** [comment]
For better or worse ensime is one of scala's saving graces. When using advanced/fancy scala intellij completely borks. So there are quite a few people that depend o ensime to get ide like features. Not having sbt 1 support (whether ensime or sbt is to blame) is a pretty big blocker to upgrading to sbt 1. (imho, the real underlying problem is sbt's rather harsh upgrade/downgrade path). 

Telling your users (that obviously depend on ensime) they aren't fit to be your users is rude and unfriendly. In general when giving an answer is as easy as giving a snarky comment, i feel it's better to give the actual answer (or stay silent if giving a clear answer is too much, it reflects better on the scala community)

**Comment by fommil** [comment]
@jrd-rocks being demanding of a contributors time, and not reading the documentation, is explicitly against our [Code of Conduct](http://ensime.org/conduct/).

The reason why we take this so seriously is because there is an illusion that contributors are there to make the life of the non-paying "user" much better. The truth of the matter is that we have to put up with excessive demands on our time with no benefit. Your friend here has privilege issues.

I couldn't expect you to understand this... look at your contribution history. You've only begun contributing. You have no idea what it's like to get multiple emails and issue reports every day with people asking you fix things for them, for free, and then being very rude to you after you give a one line answer (which is terse, but certainly not snarky) from your phone when you're sitting on the toilet, because some part of you does want to help even though you know you don't have the time to help them:

![not-many-contributions](https://user-images.githubusercontent.com/1914041/30449985-6fefa9d2-9988-11e7-8e8f-7b19769d16ab.jpg)

I have gone to great lengths to put the infrastructure and documentation in place to make it easy for people to learn what they need and contribute back. Frankly, I've spent too much time on it and I plan on stopping when I have children.

Even as I write this, my wife is telling me to get off the computer and spend time with her, which is exactly what I plan to do.

If you want to be treated like a customer, then pay the market rate for the time that you're demanding. If not, then at least follow the basic rules of conduct that we demand of you. If you want to be rude (and let me be clear in saying that I think you are both being very rude, with no apparent realisation that you are being rude) and demand the time of people who have already given you so much, then frankly go away and find somebody else to bother. These are my rules, and if you don't like them you're welcome to fork ensime and try to build your own community, but be prepared for the fact that you'll have to sacrifice your own happiness, and family time, to make it happen the way you're describing.

And thank you for mansplaining to me why sbt 1.0 is so important. If you were paying attention you would have noticed that this has been in the strategic plan for a long time, and I have spent many many hours (probably days) of my time in the discussions for what is in sbt 1.0 and ensuring that we *can* use sbt 1.0 and then making sure that we have somebody working on it (which I have paid for out of my own pocket)... but you don't see any of that, do you? You just expect "somebody" to do it for you.

**Comment by fommil** [comment]
I'm locking this thread because I honestly don't care about explaining this any further. Either you get it, or you don't. And if you don't get it by now, then you probably never will.

**Comment by fommil** [comment]
@jrd-rocks @lappalj4 heh, maybe one of you would like to apply for this position: http://ensime.org/maintainer/ you really sound like you know what you're talking about.
